# Generated by Django 4.2.1 on 2023-05-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twoD', '0004_number_value_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='num',
            field=models.CharField(max_length=3),
        ),
    ]
