# Generated by Django 4.2.1 on 2023-05-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twoD', '0005_alter_number_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
