# Generated by Django 4.2.1 on 2023-05-18 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twoD', '0006_alter_value_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('ampm', models.CharField(max_length=3)),
                ('num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_log_number', to='twoD.number')),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archiveLog', models.ManyToManyField(related_name='archive_logs', to='twoD.archivelog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
