# Generated by Django 4.2.1 on 2023-05-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twoD', '0008_remove_archivelog_date_archive_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivelog',
            name='ampm',
        ),
        migrations.AddField(
            model_name='archive',
            name='ampm',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
