# Generated by Django 4.2.1 on 2023-05-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twoD', '0009_remove_archivelog_ampm_archive_ampm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='limit',
        ),
        migrations.AddField(
            model_name='value',
            name='limit',
            field=models.IntegerField(default=99999999999),
        ),
    ]
