# Generated by Django 4.2.1 on 2023-05-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twoD', '0010_remove_number_limit_value_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivelog',
            name='limit',
            field=models.IntegerField(default=99999999999),
        ),
    ]
