# Generated by Django 4.2.1 on 2023-05-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twoD', '0011_archivelog_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='jp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
