# Generated by Django 4.2.1 on 2023-05-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twoD', '0012_archive_jp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='jp',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
