# Generated by Django 4.2.1 on 2023-06-01 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twoD', '0013_alter_archive_jp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default=99999999999)),
                ('payout_rate', models.FloatField(default=80.0)),
                ('commission', models.FloatField(default=0.12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
