# Generated by Django 4.2.1 on 2023-06-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twoD', '0015_rename_ownersetting_usersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='commission',
            field=models.FloatField(default=0.12),
        ),
        migrations.AddField(
            model_name='archive',
            name='payout_rate',
            field=models.FloatField(default=80.0),
        ),
    ]
