# Generated by Django 4.2.1 on 2023-06-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twoD', '0016_archive_commission_archive_payout_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_field',
            field=models.IntegerField(default=1000),
        ),
    ]
