# Generated by Django 4.2.1 on 2023-06-11 09:53

from django.db import migrations, models
import twoD.models


class Migration(migrations.Migration):

    dependencies = [
        ('twoD', '0017_user_random_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='random_field',
            field=models.IntegerField(default=twoD.models.generate_random_four_digits),
        ),
    ]
