# Generated by Django 4.2.1 on 2023-07-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twoD', '0018_alter_user_random_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Close',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_close', models.BooleanField(default=True)),
            ],
        ),
    ]
